### ISSUE TITLE
Doesn't work on Android Studio 2.2

### ISSUE THREAD

**Issue by nativ18** [LiveTyping/u2020-mvp-android-studio-template#1]
After I'm selecting U2020 from the new Activity window and getting the 'Configure Component' window - no matter what I do, pressing on 'done' 'cancel' or 'x' the window keeps hanging. Actually I cannot get rid of it unless I'm force closing Android studio.

I'm working on Mac

**Comment by cosic** [comment]
@nativ18 Sorry for long reaction. It's fixed if you're still interested in.

**Comment by zeeshanaslam78** [comment]
Now It's not working on Android Studio 3.0.1 
I am working on Mac.
